- name: Criando o diretorio Giropops
  file: path={{item}} state=directory
  with_items:
    - /opt/giropops
    - /opt/giropops/logs
    - /opt/giropops/conf
  register: criando_diretorios

- name: Copiando o arquivo de deployment do app para o host
  template: 
    src: app-v1.yml.j2
    dest: /opt/giropops/app-v1.yml
    owner: root
    group: root
    mode: 0644
  register: copiando_template

- name: Copiando o arquivo de servico do app para o host
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: "service-app.yml", dest: "/opt/giropops/service-app.yml" }
  register: copiando_service_file

- name: Criando o deploy do app giropops
  shell: kubectl apply -f /opt/giropops/app-v1.yml
  register: deploy_app

- name: Criando o service do app giropops
  shell: kubectl apply -f /opt/giropops/service-app.yml
  register: deploy_svc_app
